# apiVersion define a versão da API do Kubernetes que estamos usando para criar este objeto
apiVersion: apps/v1
# kind especifica o tipo de objeto que estamos criando, neste caso, um Deployment
kind: Deployment
metadata:
  # O nome do nosso Deployment
  name: video-converter
spec:
  # O número de réplicas (pods) que queremos rodando
  replicas: 2
  # O seletor define como o Deployment encontra quais pods gerenciar
  selector:
    matchLabels:
      app: video-converter
  # O template descreve os pods que serão criados
  template:
    metadata:
      # As labels aplicadas a cada pod. Deve corresponder ao seletor acima.
      labels:
        app: video-converter
      # Anotações para o Prometheus.
      # 'true' indica ao Prometheus para coletar métricas deste pod.
      # '/metrics' é o endpoint padrão que a biblioteca Flask expõe.
      # '5000' é a porta onde a aplicação está rodando e expondo as métricas.
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '5000'
    spec:
      containers:
        # Define os contêineres que rodarão dentro do pod
        - name: video-converter-container
          # A imagem Docker a ser usada. A tag 'latest' é usada aqui.
          image: video-converter:latest
          # imagePullPolicy: IfNotPresent garante que o K8s use a imagem local
          # se ela existir, em vez de tentar baixá-la de um registry.
          imagePullPolicy: IfNotPresent
          ports:
            # A porta que o contêiner expõe
            - containerPort: 5000
          # Define os recursos de CPU solicitados e os limites para o contêiner.
          # Isso é ESSENCIAL para o HPA funcionar.
          # "200m" significa 20% de um núcleo de CPU.
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"

